# Generated by Django 4.2.5 on 2025-04-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Essay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_car_topic", models.BooleanField(default=False)),
                ("car_keyword_density", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Essays",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EssayScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("car_specific_score", models.FloatField(default=0.0)),
                ("analysis_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essay",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="evaluator.essay",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Essay Scores",
                "ordering": ["-created_at"],
            },
        ),
    ]
